# Generated by Django 4.1.2 on 2022-12-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prooduct',
            new_name='Product',
        ),
    ]
